/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedVideosRouteRouteImport } from './routes/_authenticated/videos/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedPromotionsRouteRouteImport } from './routes/_authenticated/promotions/route'
import { Route as AuthenticatedParseTasksRouteRouteImport } from './routes/_authenticated/parse-tasks/route'
import { Route as AuthenticatedCrawlerRouteRouteImport } from './routes/_authenticated/crawler/route'
import { Route as AuthenticatedClubsRouteRouteImport } from './routes/_authenticated/clubs/route'
import { Route as AuthenticatedBloggersRouteRouteImport } from './routes/_authenticated/bloggers/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedParseTasksIndexRouteImport } from './routes/_authenticated/parse-tasks/index'
import { Route as AuthenticatedClubsIndexRouteImport } from './routes/_authenticated/clubs/index'
import { Route as AuthenticatedSettingsWechatWorkRouteImport } from './routes/_authenticated/settings/wechat-work'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedParseTasksIdRouteRouteImport } from './routes/_authenticated/parse-tasks/$id/route'
import { Route as AuthenticatedClubsIdRouteRouteImport } from './routes/_authenticated/clubs/$id/route'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideosRouteRoute =
  AuthenticatedVideosRouteRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionsRouteRoute =
  AuthenticatedPromotionsRouteRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParseTasksRouteRoute =
  AuthenticatedParseTasksRouteRouteImport.update({
    id: '/parse-tasks',
    path: '/parse-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrawlerRouteRoute =
  AuthenticatedCrawlerRouteRouteImport.update({
    id: '/crawler',
    path: '/crawler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClubsRouteRoute = AuthenticatedClubsRouteRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBloggersRouteRoute =
  AuthenticatedBloggersRouteRouteImport.update({
    id: '/bloggers',
    path: '/bloggers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedParseTasksIndexRoute =
  AuthenticatedParseTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParseTasksRouteRoute,
  } as any)
const AuthenticatedClubsIndexRoute = AuthenticatedClubsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedClubsRouteRoute,
} as any)
const AuthenticatedSettingsWechatWorkRoute =
  AuthenticatedSettingsWechatWorkRouteImport.update({
    id: '/wechat-work',
    path: '/wechat-work',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParseTasksIdRouteRoute =
  AuthenticatedParseTasksIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedParseTasksRouteRoute,
  } as any)
const AuthenticatedClubsIdRouteRoute =
  AuthenticatedClubsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClubsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/bloggers': typeof AuthenticatedBloggersRouteRoute
  '/clubs': typeof AuthenticatedClubsRouteRouteWithChildren
  '/crawler': typeof AuthenticatedCrawlerRouteRoute
  '/parse-tasks': typeof AuthenticatedParseTasksRouteRouteWithChildren
  '/promotions': typeof AuthenticatedPromotionsRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/videos': typeof AuthenticatedVideosRouteRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/clubs/$id': typeof AuthenticatedClubsIdRouteRoute
  '/parse-tasks/$id': typeof AuthenticatedParseTasksIdRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/wechat-work': typeof AuthenticatedSettingsWechatWorkRoute
  '/clubs/': typeof AuthenticatedClubsIndexRoute
  '/parse-tasks/': typeof AuthenticatedParseTasksIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/bloggers': typeof AuthenticatedBloggersRouteRoute
  '/crawler': typeof AuthenticatedCrawlerRouteRoute
  '/promotions': typeof AuthenticatedPromotionsRouteRoute
  '/videos': typeof AuthenticatedVideosRouteRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/clubs/$id': typeof AuthenticatedClubsIdRouteRoute
  '/parse-tasks/$id': typeof AuthenticatedParseTasksIdRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/wechat-work': typeof AuthenticatedSettingsWechatWorkRoute
  '/clubs': typeof AuthenticatedClubsIndexRoute
  '/parse-tasks': typeof AuthenticatedParseTasksIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/bloggers': typeof AuthenticatedBloggersRouteRoute
  '/_authenticated/clubs': typeof AuthenticatedClubsRouteRouteWithChildren
  '/_authenticated/crawler': typeof AuthenticatedCrawlerRouteRoute
  '/_authenticated/parse-tasks': typeof AuthenticatedParseTasksRouteRouteWithChildren
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/videos': typeof AuthenticatedVideosRouteRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clubs/$id': typeof AuthenticatedClubsIdRouteRoute
  '/_authenticated/parse-tasks/$id': typeof AuthenticatedParseTasksIdRouteRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/wechat-work': typeof AuthenticatedSettingsWechatWorkRoute
  '/_authenticated/clubs/': typeof AuthenticatedClubsIndexRoute
  '/_authenticated/parse-tasks/': typeof AuthenticatedParseTasksIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloggers'
    | '/clubs'
    | '/crawler'
    | '/parse-tasks'
    | '/promotions'
    | '/settings'
    | '/videos'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/clubs/$id'
    | '/parse-tasks/$id'
    | '/errors/$error'
    | '/settings/ai'
    | '/settings/wechat-work'
    | '/clubs/'
    | '/parse-tasks/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bloggers'
    | '/crawler'
    | '/promotions'
    | '/videos'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/clubs/$id'
    | '/parse-tasks/$id'
    | '/errors/$error'
    | '/settings/ai'
    | '/settings/wechat-work'
    | '/clubs'
    | '/parse-tasks'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/bloggers'
    | '/_authenticated/clubs'
    | '/_authenticated/crawler'
    | '/_authenticated/parse-tasks'
    | '/_authenticated/promotions'
    | '/_authenticated/settings'
    | '/_authenticated/videos'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/clubs/$id'
    | '/_authenticated/parse-tasks/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/wechat-work'
    | '/_authenticated/clubs/'
    | '/_authenticated/parse-tasks/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parse-tasks': {
      id: '/_authenticated/parse-tasks'
      path: '/parse-tasks'
      fullPath: '/parse-tasks'
      preLoaderRoute: typeof AuthenticatedParseTasksRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crawler': {
      id: '/_authenticated/crawler'
      path: '/crawler'
      fullPath: '/crawler'
      preLoaderRoute: typeof AuthenticatedCrawlerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clubs': {
      id: '/_authenticated/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AuthenticatedClubsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bloggers': {
      id: '/_authenticated/bloggers'
      path: '/bloggers'
      fullPath: '/bloggers'
      preLoaderRoute: typeof AuthenticatedBloggersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/parse-tasks/': {
      id: '/_authenticated/parse-tasks/'
      path: '/'
      fullPath: '/parse-tasks/'
      preLoaderRoute: typeof AuthenticatedParseTasksIndexRouteImport
      parentRoute: typeof AuthenticatedParseTasksRouteRoute
    }
    '/_authenticated/clubs/': {
      id: '/_authenticated/clubs/'
      path: '/'
      fullPath: '/clubs/'
      preLoaderRoute: typeof AuthenticatedClubsIndexRouteImport
      parentRoute: typeof AuthenticatedClubsRouteRoute
    }
    '/_authenticated/settings/wechat-work': {
      id: '/_authenticated/settings/wechat-work'
      path: '/wechat-work'
      fullPath: '/settings/wechat-work'
      preLoaderRoute: typeof AuthenticatedSettingsWechatWorkRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parse-tasks/$id': {
      id: '/_authenticated/parse-tasks/$id'
      path: '/$id'
      fullPath: '/parse-tasks/$id'
      preLoaderRoute: typeof AuthenticatedParseTasksIdRouteRouteImport
      parentRoute: typeof AuthenticatedParseTasksRouteRoute
    }
    '/_authenticated/clubs/$id': {
      id: '/_authenticated/clubs/$id'
      path: '/$id'
      fullPath: '/clubs/$id'
      preLoaderRoute: typeof AuthenticatedClubsIdRouteRouteImport
      parentRoute: typeof AuthenticatedClubsRouteRoute
    }
  }
}

interface AuthenticatedClubsRouteRouteChildren {
  AuthenticatedClubsIdRouteRoute: typeof AuthenticatedClubsIdRouteRoute
  AuthenticatedClubsIndexRoute: typeof AuthenticatedClubsIndexRoute
}

const AuthenticatedClubsRouteRouteChildren: AuthenticatedClubsRouteRouteChildren =
  {
    AuthenticatedClubsIdRouteRoute: AuthenticatedClubsIdRouteRoute,
    AuthenticatedClubsIndexRoute: AuthenticatedClubsIndexRoute,
  }

const AuthenticatedClubsRouteRouteWithChildren =
  AuthenticatedClubsRouteRoute._addFileChildren(
    AuthenticatedClubsRouteRouteChildren,
  )

interface AuthenticatedParseTasksRouteRouteChildren {
  AuthenticatedParseTasksIdRouteRoute: typeof AuthenticatedParseTasksIdRouteRoute
  AuthenticatedParseTasksIndexRoute: typeof AuthenticatedParseTasksIndexRoute
}

const AuthenticatedParseTasksRouteRouteChildren: AuthenticatedParseTasksRouteRouteChildren =
  {
    AuthenticatedParseTasksIdRouteRoute: AuthenticatedParseTasksIdRouteRoute,
    AuthenticatedParseTasksIndexRoute: AuthenticatedParseTasksIndexRoute,
  }

const AuthenticatedParseTasksRouteRouteWithChildren =
  AuthenticatedParseTasksRouteRoute._addFileChildren(
    AuthenticatedParseTasksRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsWechatWorkRoute: typeof AuthenticatedSettingsWechatWorkRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
    AuthenticatedSettingsWechatWorkRoute: AuthenticatedSettingsWechatWorkRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBloggersRouteRoute: typeof AuthenticatedBloggersRouteRoute
  AuthenticatedClubsRouteRoute: typeof AuthenticatedClubsRouteRouteWithChildren
  AuthenticatedCrawlerRouteRoute: typeof AuthenticatedCrawlerRouteRoute
  AuthenticatedParseTasksRouteRoute: typeof AuthenticatedParseTasksRouteRouteWithChildren
  AuthenticatedPromotionsRouteRoute: typeof AuthenticatedPromotionsRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedVideosRouteRoute: typeof AuthenticatedVideosRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBloggersRouteRoute: AuthenticatedBloggersRouteRoute,
  AuthenticatedClubsRouteRoute: AuthenticatedClubsRouteRouteWithChildren,
  AuthenticatedCrawlerRouteRoute: AuthenticatedCrawlerRouteRoute,
  AuthenticatedParseTasksRouteRoute:
    AuthenticatedParseTasksRouteRouteWithChildren,
  AuthenticatedPromotionsRouteRoute: AuthenticatedPromotionsRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedVideosRouteRoute: AuthenticatedVideosRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
